language: python
python:
  - "3.6"


services: sqlite3

env:
  - DJANGO=2.0

before_install:
  - export DJANGO_SETTINGS_MODULE=Web-data-labelling.settings
  - export PYTHONPATH=$HOME/builds/SimbarasheJehol/Web-data-labelling
  - export PIP_USE_MIRRORS=true

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install coverage
  - pip install Django
  - pip install pathlib
  - pip install codecov


before_script:
 # - sqlite3 -e "CREATE DATABASE mydb;"

# command to run tests
script:
  #- python manage.py 

after_success:
  - coveralls
- codecov
