dist: xenial
language: python
python:
  - "3.6"


services: sqlite3

env:
  - DJANGO=2.0
  #- DJANGO=1.11.20

before_install:
  - export DJANGO_SETTINGS_MODULE=dineos_boys.settings

  - export DJANGO_SETTINGS_MODULE=Timetable.settings
  - export PIP_USE_MIRRORS=true
  - export PYTHONPATH=$HOME/builds/Motaung08/TimetableG
  - BUILD_ON_TRAVIS=true

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install coverage
  - pip install Django
  - pip install pathlib
  - pip install django-nose
  - pip install codecov

before_script:

  #- mysql -e "CREATE DATABASE travis_ci_db;"


  #- sqlite3 -e "CREATE DATABASE mydb;"


# command to run tests
script:
  - python manage.py test
  #- coverage run manage.py
  # - coverage run ./Register/urls.py
  #- pytest
  #- coverage run ./Register/models.py
  #- coverage run ./Timetable/Tests/test_views.py 1

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - coveralls
  - codecov
