language: python
python:
  - "3.6"


services: sqlite3

env:
  - DJANGO=2.0

before_install:
  - export DJANGO_SETTINGS_MODULE=Web-data-labelling.settings
  - export PYTHONPATH=$HOME/builds/SimbarasheJehol/Web-data-labelling
  - export PIP_USE_MIRRORS=true

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install coverage
  - pip install Django
  - pip install pathlib
  - pip install codecov


before_script:
 # - sqlite3 -e "CREATE DATABASE mydb;"

# command to run tests
script:
  #- python ./manage.py test 
  #- python ./TimetableGen/manage.py 
  - python ./manage.py
  
 
  
  #- coverage run ./Timetable/Register/tests.py
  #- coverage run ./Timetable/manage.py TimetableG.Timetable.tests.tests
  #- coverage run ./test.py
  - coverage run ./loggedin/tests.py
  #- coverage run  ./loggedin/test_views.py
  - coverage run ./Register/tests.py
  # coverage run ./TimetableG/loggedin/tests.py 1
  #- coverage run ./Timetable/loggedin/tests.py 
  #- coverage run  ./Timetable/tests/tests.py
  #- coverage run  ./TimetableGen/Register/tests.py 
  #- coverage run  ./loggedin/tests.py 
  #- coverage run ./Timetable/Tests/test_views.py 1
  
after_success:
  - coveralls
  - codecov
