language: python
python:
  - "3.6"


services: sqlite3

env:
  - DJANGO=2.0

before_install:
  - export DJANGO_SETTINGS_MODULE=Web-data-labelling.settings
  - export PYTHONPATH=$HOME/builds/SimbarasheJehol/Web-data-labelling
  - export PIP_USE_MIRRORS=true

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install coverage
  - pip install Django
  - pip install pathlib
  - pip install codecov


before_script:
 # - sqlite3 -e "CREATE DATABASE mydb;"

# command to run tests
script:
  - python ./Timetable/manage.py test
  #- pytest
  #- coverage run ./Timetable/Register/tests.py 1
  #- coverage run ./Timetable/loggedin/tests.py 1
  - coverage run ./Timetable/loggedin/tests_urls.py 
  #- coverage run ./Timetable/Register/tests_views.py 
  #- coverage run ./Timetable/Tests/test_views.py 1
  
after_success:
  - coveralls
  - codecov
